In [1]:
#Question 1
import pandas as pd
import numpy as np
data = {'Name':['Shivani_Bansal', 'Sheenu_Bansal'], 'Age':[21,21],'Email_id':['shivani1815.cse16@chitkara.edu.in','bsheenu2@gmail.com'],'phone_number':[1234567890,98765432]}
df = pd.DataFrame(data)
print(df)

             Name  Age                           Email_id  phone_number
0  Shivani_Bansal   21  shivani1815.cse16@chitkara.edu.in    1234567890
1   Sheenu_Bansal   21                 bsheenu2@gmail.com      98765432

In [17]:
#Question 2
#A
import pandas as pd
df = pd.read_csv(r'C:\Users\DELL\Desktop\python1\weather.csv')

df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11/1/2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11/2/2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11/3/2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11/4/2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11/5/2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [18]:
#B
df.head(10)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11/1/2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11/2/2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11/3/2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11/4/2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11/5/2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,11/6/2007,Canberra,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,11/7/2007,Canberra,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,11/8/2007,Canberra,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,11/9/2007,Canberra,8.8,19.5,0.0,4.0,4.1,S,48.0,E,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,11/10/2007,Canberra,8.4,22.8,16.2,5.4,7.7,E,31.0,S,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [19]:
#C
print(df.sum())

Date             11/1/200711/2/200711/3/200711/4/200711/5/20071...
Location         CanberraCanberraCanberraCanberraCanberraCanber...
MinTemp                                                     2659.2
MaxTemp                                                     7521.4
Rainfall                                                     522.8
Evaporation                                                   1655
Sunshine                                                    2871.1
WindGustSpeed                                                14502
WindSpeed9am                                                  3465
WindSpeed3pm                                                  6583
Humidity9am                                                  26365
Humidity3pm                                                  16294
Pressure9am                                                 373214
Pressure3pm                                                 372153
Cloud9am                                                      1424
Cloud3pm                                                      1473
Temp9am                                                     4523.2
Temp3pm                                                     7038.5
RainToday        NoYesYesYesYesNoNoNoNoYesNoNoNoNoNoNoNoYesNoNo...
RISK_MM                                                      522.8
RainTomorrow     YesYesYesYesNoNoNoNoYesNoNoNoNoNoNoNoYesNoNoNo...
dtype: object

In [20]:

print(df.mean())

MinTemp             7.265574
MaxTemp            20.550273
Rainfall            1.428415
Evaporation         4.521858
Sunshine            7.909366
WindGustSpeed      39.840659
WindSpeed9am        9.651811
WindSpeed3pm       17.986339
Humidity9am        72.035519
Humidity3pm        44.519126
Pressure9am      1019.709016
Pressure3pm      1016.810383
Cloud9am            3.890710
Cloud3pm            4.024590
Temp9am            12.358470
Temp3pm            19.230874
RISK_MM             1.428415
dtype: float64

In [21]:
print(df.std())

MinTemp           6.025800
MaxTemp           6.690516
Rainfall          4.225800
Evaporation       2.669383
Sunshine          3.481517
WindGustSpeed    13.059807
WindSpeed9am      7.951929
WindSpeed3pm      8.856997
Humidity9am      13.137058
Humidity3pm      16.850947
Pressure9am       6.686212
Pressure3pm       6.469422
Cloud9am          2.956131
Cloud3pm          2.666268
Temp9am           5.630832
Temp3pm           6.640346
RISK_MM           4.225800
dtype: float64

In [22]:
print(df.describe())

          MinTemp     MaxTemp    Rainfall  Evaporation    Sunshine  \
count  366.000000  366.000000  366.000000   366.000000  363.000000
mean     7.265574   20.550273    1.428415     4.521858    7.909366
std      6.025800    6.690516    4.225800     2.669383    3.481517
min     -5.300000    7.600000    0.000000     0.200000    0.000000
25%      2.300000   15.025000    0.000000     2.200000    5.950000
50%      7.450000   19.650000    0.000000     4.200000    8.600000
75%     12.500000   25.500000    0.200000     6.400000   10.500000
max     20.900000   35.800000   39.800000    13.800000   13.600000

       WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
count     364.000000    359.000000    366.000000   366.000000   366.000000
mean       39.840659      9.651811     17.986339    72.035519    44.519126
std        13.059807      7.951929      8.856997    13.137058    16.850947
min        13.000000      0.000000      0.000000    36.000000    13.000000
25%        31.000000      6.000000     11.000000    64.000000    32.250000
50%        39.000000      7.000000     17.000000    72.000000    43.000000
75%        46.000000     13.000000     24.000000    81.000000    55.000000
max        98.000000     41.000000     52.000000    99.000000    96.000000

       Pressure9am  Pressure3pm    Cloud9am    Cloud3pm     Temp9am  \
count   366.000000   366.000000  366.000000  366.000000  366.000000
mean   1019.709016  1016.810383    3.890710    4.024590   12.358470
std       6.686212     6.469422    2.956131    2.666268    5.630832
min     996.500000   996.800000    0.000000    0.000000    0.100000
25%    1015.350000  1012.800000    1.000000    1.000000    7.625000
50%    1020.150000  1017.400000    3.500000    4.000000   12.550000
75%    1024.475000  1021.475000    7.000000    7.000000   17.000000
max    1035.700000  1033.200000    8.000000    8.000000   24.700000

          Temp3pm     RISK_MM
count  366.000000  366.000000
mean    19.230874    1.428415
std      6.640346    4.225800
min      5.100000    0.000000
25%     14.150000    0.000000
50%     18.550000    0.000000
75%     24.000000    0.200000
max     34.500000   39.800000

In [23]:
print(df.describe(include='all'))

             Date  Location     MinTemp     MaxTemp    Rainfall  Evaporation  \
count         366       366  366.000000  366.000000  366.000000   366.000000
unique        366         1         NaN         NaN         NaN          NaN
top     6/28/2008  Canberra         NaN         NaN         NaN          NaN
freq            1       366         NaN         NaN         NaN          NaN
mean          NaN       NaN    7.265574   20.550273    1.428415     4.521858
std           NaN       NaN    6.025800    6.690516    4.225800     2.669383
min           NaN       NaN   -5.300000    7.600000    0.000000     0.200000
25%           NaN       NaN    2.300000   15.025000    0.000000     2.200000
50%           NaN       NaN    7.450000   19.650000    0.000000     4.200000
75%           NaN       NaN   12.500000   25.500000    0.200000     6.400000
max           NaN       NaN   20.900000   35.800000   39.800000    13.800000

          Sunshine WindGustDir  WindGustSpeed WindDir9am      ...       \
count   363.000000         363     364.000000        335      ...
unique         NaN          16            NaN         16      ...
top            NaN          NW            NaN         SE      ...
freq           NaN          73            NaN         47      ...
mean      7.909366         NaN      39.840659        NaN      ...
std       3.481517         NaN      13.059807        NaN      ...
min       0.000000         NaN      13.000000        NaN      ...
25%       5.950000         NaN      31.000000        NaN      ...
50%       8.600000         NaN      39.000000        NaN      ...
75%      10.500000         NaN      46.000000        NaN      ...
max      13.600000         NaN      98.000000        NaN      ...

       Humidity3pm  Pressure9am  Pressure3pm    Cloud9am    Cloud3pm  \
count   366.000000   366.000000   366.000000  366.000000  366.000000
unique         NaN          NaN          NaN         NaN         NaN
top            NaN          NaN          NaN         NaN         NaN
freq           NaN          NaN          NaN         NaN         NaN
mean     44.519126  1019.709016  1016.810383    3.890710    4.024590
std      16.850947     6.686212     6.469422    2.956131    2.666268
min      13.000000   996.500000   996.800000    0.000000    0.000000
25%      32.250000  1015.350000  1012.800000    1.000000    1.000000
50%      43.000000  1020.150000  1017.400000    3.500000    4.000000
75%      55.000000  1024.475000  1021.475000    7.000000    7.000000
max      96.000000  1035.700000  1033.200000    8.000000    8.000000

           Temp9am     Temp3pm  RainToday     RISK_MM  RainTomorrow
count   366.000000  366.000000        366  366.000000           366
unique         NaN         NaN          2         NaN             2
top            NaN         NaN         No         NaN            No
freq           NaN         NaN        300         NaN           300
mean     12.358470   19.230874        NaN    1.428415           NaN
std       5.630832    6.640346        NaN    4.225800           NaN
min       0.100000    5.100000        NaN    0.000000           NaN
25%       7.625000   14.150000        NaN    0.000000           NaN
50%      12.550000   18.550000        NaN    0.000000           NaN
75%      17.000000   24.000000        NaN    0.200000           NaN
max      24.700000   34.500000        NaN   39.800000           NaN

[11 rows x 24 columns]

In [24]:
#D
df.tail(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,10/27/2008,Canberra,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,10/28/2008,Canberra,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,10/29/2008,Canberra,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,10/30/2008,Canberra,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,10/31/2008,Canberra,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [43]:
#E
w=df.loc[df['Date'] == '11/3/2007']
print(w)

        Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
2  11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
2          NW           85.0          N      ...               69

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
2       1009.5       1007.2         8         7     15.4     20.2        Yes

   RISK_MM  RainTomorrow
2     39.8           Yes

[1 rows x 24 columns]

In [38]:
print(w.sum())

Date             11/3/2007
Location          Canberra
MinTemp               13.7
MaxTemp               23.4
Rainfall               3.6
Evaporation            5.8
Sunshine               3.3
WindGustDir             NW
WindGustSpeed           85
WindDir9am               N
WindDir3pm             NNE
WindSpeed9am             6
WindSpeed3pm             6
Humidity9am             82
Humidity3pm             69
Pressure9am         1009.5
Pressure3pm         1007.2
Cloud9am                 8
Cloud3pm                 7
Temp9am               15.4
Temp3pm               20.2
RainToday              Yes
RISK_MM               39.8
RainTomorrow           Yes
dtype: object

In [40]:
print(w.mean())

MinTemp            13.7
MaxTemp            23.4
Rainfall            3.6
Evaporation         5.8
Sunshine            3.3
WindGustSpeed      85.0
WindSpeed9am        6.0
WindSpeed3pm        6.0
Humidity9am        82.0
Humidity3pm        69.0
Pressure9am      1009.5
Pressure3pm      1007.2
Cloud9am            8.0
Cloud3pm            7.0
Temp9am            15.4
Temp3pm            20.2
RISK_MM            39.8
dtype: float64

In [41]:
print(w.std())

MinTemp         NaN
MaxTemp         NaN
Rainfall        NaN
Evaporation     NaN
Sunshine        NaN
WindGustSpeed   NaN
WindSpeed9am    NaN
WindSpeed3pm    NaN
Humidity9am     NaN
Humidity3pm     NaN
Pressure9am     NaN
Pressure3pm     NaN
Cloud9am        NaN
Cloud3pm        NaN
Temp9am         NaN
Temp3pm         NaN
RISK_MM         NaN
dtype: float64